apiVersion: v1
kind: Service
metadata:
  name: "backend-service"
  namespace: helm
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.backend.service.servicePort }}
    nodePort: 30555
  type: NodePort
  selector:
    app: "backend-selector"