apiVersion: v1
kind: Service
metadata:
  name: "frontend-service"
  namespace: helm
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.frontend.service.servicePort }}
    nodePort: 30444
  type: {{ .Values.frontend.service.type }}
  selector:
    app: "frontend-selector"
