apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo
        ports:
        - name: mongodb-port
          containerPort: 27017
          protocol: TCP
        